### ISSUE TITLE
No control for widget 'youtube'.

### ISSUE THREAD

**Issue by derevandal** [hennessyevan/netlify-cms-widget-youtube#2]
## Actual Behavior
The widget doesn't load.

![image](https://user-images.githubusercontent.com/1340508/60940626-7d34c700-a2b2-11e9-96db-b79e9f793558.png)

**index.js**
```js
import CMS from 'netlify-cms'
import { youtubeControl, youtubePreview } from 'netlify-cms-widget-youtube'
CMS.registerWidget('youtube', youtubeControl, youtubePreview)
```

I tried `import youtube from 'netlify-cms-widget-youtube'` too

**config.yml**
```yml
      - label: "Galeria: Vídeos"
        name: "videos-gallery"
        file: "content/gallery/videos.yml"
        fields:
          - label: "Vídeo"
            name: "videos"
            widget: "list"
            fields:
            - { name: video, label: Vídeo, widget: youtube, extraInfo: true, APIkey: "" }
```

## Specifications

- netlify-cms-app 2.9.5
- netlify-cms-core 2.12.1
- netlify-cms 2.9.5
